/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SceneData {
	[k: string]: SceneInfo;
}
export interface SceneInfo {
	name: string;
	hideTimer?: boolean;
	run: RunData | null;
	camStack?: {
		[k: string]: {
			direction?: 'horizontal' | 'vertical';
			gap?: number;
			cams?: string[];
			[k: string]: unknown;
		};
	};
	cams?: {
		[k: string]: Cam;
	};
	[k: string]: unknown;
}
export interface RunData {
	game?: string;
	gameTwitch?: string;
	system?: string;
	region?: string;
	release?: string;
	category?: string;
	estimate?: string;
	estimateS?: number;
	setupTime?: string;
	setupTimeS?: number;
	scheduled?: string;
	scheduledS?: number;
	relay?: boolean;
	teams: {
		name?: string;
		id: string;
		relayPlayerID?: string;
		players: {
			name: string;
			id: string;
			teamID: string;
			country?: string;
			pronouns?: string;
			social: {
				twitch?: string;
				youtube?: string;
			};
			customData: {
				[k: string]: string;
			};
		}[];
	}[];
	customData: {
		[k: string]: string;
	};
	id: string;
	externalID?: string;
}
export interface Cam {
	sourceName: string;
	crop?: 'start' | 'center' | 'end' | 'custom';
	aspectRatio?: string;
	label?: string;
	[k: string]: unknown;
}
