/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Screen = (CellData | null)[];

export interface Display {
	current: string;
	pages: {
		default: Page;
		[k: string]: Page;
	};
}
export interface Page {
	screen: Screen;
	interactions: {
		knobs: Knobs;
		[k: string]: unknown;
	};
	[k: string]: unknown;
}
export interface CellData {
	text?: string;
	colour?: string;
	bg?: string;
	imgType?: 'svg' | 'png' | 'svgURL' | 'pngURL' | 'base64';
	img?: string;
	[k: string]: unknown;
}
export interface Knobs {
	/**
	 * @minItems 2
	 * @maxItems 2
	 */
	channels: [string | null, string | null];
	rotateScale: number;
	[k: string]: unknown;
}
