/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * @minItems 15
 * @maxItems 15
 */
export type Screen = [
	CellData | null,
	CellData | null,
	CellData | null,
	CellData | null,
	CellData | null,
	CellData | null,
	CellData | null,
	CellData | null,
	CellData | null,
	CellData | null,
	CellData | null,
	CellData | null,
	CellData | null,
	CellData | null,
	CellData | null
];
export type Condition = {
	replicant: string;
	field: string;
	operator: '=' | '!=' | '<' | '<=' | '>' | '>=' | 'exists' | 'not exists';
	values: unknown[];
}[];

export interface Display {
	current: string;
	pages: {
		default: Page;
		[k: string]: Page;
	};
}
export interface Page {
	screen: Screen;
	knobs?: Knobs;
	/**
	 * @minItems 4
	 * @maxItems 4
	 */
	buttons?: [null | State, null | State, null | State, null | State];
	[k: string]: unknown;
}
export interface CellData {
	replicants?: {
		[k: string]:
			| string
			| {
					replicant: string;
					bundle: string | null;
			  };
	};
	states: {
		[k: string]: State;
	};
}
export interface State {
	graphic?: Graphic;
	isActive?: Condition;
	interaction?: null | TapOrToggle | NodecgMsg | NodecgReplicant;
	[k: string]: unknown;
}
export interface Graphic {
	text?: string;
	colour?: string;
	bg?: string;
	imgType?: 'svg' | 'png' | 'svgURL' | 'pngURL' | 'base64';
	img?: string;
}
export interface TapOrToggle {
	category: 'modifier';
	action: 'tap-or-toggle';
	interaction: null | TapOrToggle | NodecgMsg | NodecgReplicant;
	[k: string]: unknown;
}
export interface NodecgMsg {
	category: 'nodecg';
	action: 'message';
	message: string;
	data?: unknown;
	bundle?: string | null;
	[k: string]: unknown;
}
export interface NodecgReplicant {
	category: 'nodecg';
	action: 'replicant';
	replicant:
		| string
		| {
				replicant: string;
				bundle: string | null;
		  };
	field: string;
	value: unknown;
	[k: string]: unknown;
}
export interface Knobs {
	/**
	 * @minItems 2
	 * @maxItems 2
	 */
	channels: [string | null, string | null];
	rotateScale: number;
	/**
	 * @minItems 2
	 * @maxItems 2
	 */
	buttons: [null | State, null | State];
	[k: string]: unknown;
}
