/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Interactions {
	knobs: {
		/**
		 * @minItems 2
		 * @maxItems 2
		 */
		channels: [string | null, string | null];
		rotateScale: number;
		[k: string]: unknown;
	};
	[k: string]: unknown;
}
