/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface People {
	all: Category;
	[k: string]: Category;
}
export interface Category {
	name: string;
	people: string[];
	icon?: Icon;
	hide?: boolean;
	[k: string]: unknown;
}
export interface Icon {
	iconType: 'svg';
	name?: string;
	icon: string;
	[k: string]: unknown;
}
