/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AnnBank {
	[k: string]: Announcement;
}
export interface Announcement {
	type?: string;
	priority: number;
	text: string;
	[k: string]: unknown;
}
