/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AnnouncementPool {
	name: string;
	priority: number;
	items: Announcement[];
	[k: string]: unknown;
}
export interface Announcement {
	id: string;
	text: string;
	repeat: boolean;
	priority: number;
	[k: string]: unknown;
}
