/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AnnQueue {
	name: string;
	priority: number;
	announcements: AnnRef[];
	[k: string]: unknown;
}
export interface AnnRef {
	id: string;
	time?: number;
	[k: string]: unknown;
}
