/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PeopleBank {
	[k: string]: Person;
}
export interface Person {
	name: string;
	socials: Social[];
	[k: string]: unknown;
}
export interface Social {
	id: string;
	social: string;
	name: string;
	[k: string]: unknown;
}
