/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Current {
	text: string | null;
	msgID: string | null;
	endTime: number;
	startTime: number;
	time?: number;
	pause?: boolean;
	[k: string]: unknown;
}
