/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ConnStatus = 'connected' | 'connecting' | 'disconnected' | 'error' | 'retrying';

/**
 * Status of OBS outputs
 */
export interface Status {
	connected: ConnStatus;
	streaming: boolean;
	recording: boolean;
	transitioning: boolean;
	studioMode: boolean;
	moveCams: boolean;
	controlRecording: boolean;
}
